server:
  port: 9001
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mekanapp_users
    username: postgres
    password: 159753
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: util_sch

## Actuator ##
management:
  endpoints:
    web:
      exposure:
        include: health,info

## OpenApi Settings ##
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: "/docs/swagger-ui.html"

openapi:
  app:
    title: "VolSys Utility API"
    description: "This project aims to provide utility operations for all VolSys services."
    version: 1.0
    contact : "Contact Support"
    email: "info@talls.tech"
    licence: "Tallstech 1.0"
    url: "https://www.talls.tech"
